const NATURAL_LANGUAGE_UNDERSTANDING_APIKEY =

const NATURAL_LANGUAGE_UNDERSTANDING_IAM_APIKEY =

const NATURAL_LANGUAGE_UNDERSTANDING_URL =

const NATURAL_LANGUAGE_UNDERSTANDING_AUTH_TYPE = "iam";
